# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qfluentwidgets import (LineEdit, PasswordLineEdit, PrimaryPushButton)
from qfluentwidgets import InfoBar, InfoBarIcon, InfoBarPosition, setThemeColor



class Ui_Login(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(390, 200)
        self.setFixedSize(390, 200)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(39, 27, 54, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(39, 88, 54, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.studentNo = LineEdit(Form)
        self.studentNo.setGeometry(QtCore.QRect(100, 27, 256, 38))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.studentNo.setFont(font)
        self.studentNo.setText("")
        self.studentNo.setMaxLength(20)
        self.studentNo.setObjectName("studentNo")
        self.password = PasswordLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(100, 88, 256, 38))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.pushButton = PrimaryPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(50, 140, 301, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录"))
        self.label.setText(_translate("Form", "学号"))
        self.label_2.setText(_translate("Form", "密码"))
        self.pushButton.setText(_translate("Form", "登录"))


class login_window(QtWidgets.QWidget, Ui_Login):
    '''
    登录窗口
    '''
    login_signal = QtCore.pyqtSignal(str, str)
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowModality(QtCore.Qt.ApplicationModal)
        self.setFixedSize(390, 200)
        self.studentNo.setFocus()

        self.studentNo.returnPressed.connect(self.password.setFocus)
        self.password.returnPressed.connect(self.pushButton.click)
        self.pushButton.clicked.connect(self.login)

        setThemeColor("#940c8a")

    def login(self):
        uname = self.studentNo.text()
        passwd = self.password.text()
        if uname == "" or passwd == "":
            infobar = InfoBar(InfoBarIcon.ERROR, "登录失败", "学号或密码不能为空！",
                              position=InfoBarPosition.TOP, parent=self)
            infobar.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.WindowStaysOnTopHint)
            infobar.show()
            return

        self.studentNo.setEnabled(False)
        self.password.setEnabled(False)
        self.pushButton.setEnabled(False)
        self.pushButton.setText("登录中...")
        QtWidgets.QApplication.processEvents()
        self.login_signal.emit(self.studentNo.text(), self.password.text())

    def show(self):
        self.studentNo.setEnabled(True)
        self.password.setEnabled(True)
        self.pushButton.setEnabled(True)
        self.pushButton.setText("登录")
        super().show()


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = login_window()

    login.show()
    sys.exit(app.exec_())    
